"""
services/safety_engine.py
==========================
Clinical Safety Engine — validates AI outputs before surfacing to clinicians.

v2 improvements:
  - HIGH_RISK_DISEASES set: auto-escalate regardless of confidence
  - Zoonotic & notifiable disease alerts
  - Clinical urgency score (1-10)
  - Smarter risk stratification
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional, Set

logger = logging.getLogger(__name__)


# ── Safety levels ─────────────────────────────────────────────────────────────

class SafetyLevel:
    PASS    = "pass"
    WARNING = "warning"
    BLOCKED = "blocked"


# ── Main engine ───────────────────────────────────────────────────────────────

class ClinicalSafetyEngine:
    """
    Gate-keeper that validates every AI prediction before it reaches the API
    response layer.

    Rules applied (in order)
    ------------------------
    1. HIGH_RISK diseases → auto-escalate to 'warning' regardless of confidence
    2. NOTIFIABLE diseases → hard warning + notification flag
    3. Low-confidence predictions → downgraded / flagged
    4. High model uncertainty → recommendations blocked
    5. Dosing requests without animal weight → hard block
    6. Clinical urgency score computed from all signals
    7. Clinical disclaimer injected on every output
    """

    DISCLAIMER = (
        "⚠️  SAFETY NOTICE: This report is generated by an AI system intended "
        "to support — not replace — a licensed veterinarian. "
        "Treatment decisions must be made by qualified veterinary professionals."
    )

    # Diseases that warrant escalation regardless of confidence
    HIGH_RISK_DISEASES: Set[str] = {
        "oral_lesion",       # FMD — notifiable, highly contagious
        "skin_nodules",      # LSD — notifiable, OIE-listed
        "neurological_sign", # BSE / listeriosis — zoonotic risk
        "abdominal_pain",    # potential surgical emergency (LDA volvulus)
        "diarrhea",          # zoonotic (Salmonella, Cryptosporidium)
    }

    # Diseases that are zoonotic or notifiable (must alert farm workers / authorities)
    NOTIFIABLE_DISEASES: Set[str] = {"oral_lesion", "skin_nodules"}
    ZOONOTIC_DISEASES: Set[str] = {
        "oral_lesion", "skin_nodules", "neurological_sign", "diarrhea", "skin_lesion"
    }

    def __init__(
        self,
        min_confidence: float = 0.60,
        require_weight_for_dosing: bool = True,
        block_uncertain: bool = True,
        uncertainty_block_threshold: float = 0.25,
    ) -> None:
        self.min_confidence       = min_confidence
        self.require_weight       = require_weight_for_dosing
        self.block_uncertain      = block_uncertain
        self.uncertainty_threshold= uncertainty_block_threshold

    # ── Primary validation interface ──────────────────────────────────────────

    def validate_predictions(
        self,
        disease_predictions: List[Dict[str, Any]],
        model_uncertainty: float,
        animal_weight_kg: Optional[float] = None,
    ) -> Dict[str, Any]:
        """
        Validate disease-classification predictions.

        Returns
        -------
        {
            "safety_level":          "pass" | "warning" | "blocked",
            "validated_predictions": [...],
            "safety_flags":          [...],
            "allow_dosing":          bool,
            "clinical_urgency":      int (1-10),
            "zoonotic_diseases":     [...],
            "notifiable_diseases":   [...],
        }
        """
        flags: List[str] = []
        safety_level = SafetyLevel.PASS
        zoonotic_found: List[str] = []
        notifiable_found: List[str] = []

        # ── Rule 1: HIGH_RISK disease auto-escalation ────────────────────────
        for pred in disease_predictions:
            disease = pred.get("disease", "")
            if disease in self.HIGH_RISK_DISEASES:
                if safety_level == SafetyLevel.PASS:
                    safety_level = SafetyLevel.WARNING
                flags.append(
                    f"🔴 High-risk disease detected: {disease.replace('_',' ').title()} "
                    f"(confidence {pred.get('confidence', 0):.1%}) — clinical evaluation advised."
                )

        # ── Rule 2: Notifiable / zoonotic disease alerts ─────────────────────
        for pred in disease_predictions:
            disease = pred.get("disease", "")
            if disease in self.NOTIFIABLE_DISEASES:
                notifiable_found.append(disease)
                safety_level = SafetyLevel.BLOCKED
                flags.append(
                    f"🚨 NOTIFIABLE DISEASE suspected: {disease}. "
                    "Immediate notification to veterinary authorities REQUIRED."
                )
            if disease in self.ZOONOTIC_DISEASES:
                zoonotic_found.append(disease)
                if safety_level == SafetyLevel.PASS:
                    safety_level = SafetyLevel.WARNING
                flags.append(
                    f"⚠️ ZOONOTIC RISK: {disease} — implement biosecurity measures "
                    "for farm workers (PPE, hand hygiene, restricted access)."
                )

        # ── Rule 3: filter low-confidence predictions ────────────────────────
        validated = []
        for pred in disease_predictions:
            conf = pred.get("confidence", 0)
            if conf >= self.min_confidence:
                validated.append({**pred, "safety_validated": True})
            else:
                validated.append({
                    **pred,
                    "safety_validated": False,
                    "safety_note": f"Confidence {conf:.1%} below threshold {self.min_confidence:.1%}",
                })
                if safety_level == SafetyLevel.PASS:
                    safety_level = SafetyLevel.WARNING
                flags.append(
                    f"Low-confidence prediction: {pred.get('disease')} ({conf:.1%})"
                )

        # ── Rule 4: high model uncertainty ──────────────────────────────────
        if self.block_uncertain and model_uncertainty > self.uncertainty_threshold:
            safety_level = SafetyLevel.BLOCKED
            flags.append(
                f"Model uncertainty {model_uncertainty:.3f} exceeds threshold "
                f"{self.uncertainty_threshold:.3f}. Recommendations blocked."
            )

        # ── Rule 5: dosing safety ────────────────────────────────────────────
        allow_dosing = True
        
        # 1. Block if weight is missing (standard safety)
        if self.require_weight and animal_weight_kg is None:
            allow_dosing = False
            flags.append("Animal weight not provided — dosing recommendations disabled.")
            if safety_level == SafetyLevel.PASS:
                safety_level = SafetyLevel.WARNING

        # 2. Hard block if case is BLOCKED or NOTIFIABLE (critical safety)
        if safety_level == SafetyLevel.BLOCKED or notifiable_found:
            allow_dosing = False
            if notifiable_found:
                flags.append("🚨 DOSING PROHIBITED: Potential notifiable disease outbreak suspected. Refer to veterinary authorities.")
            elif safety_level == SafetyLevel.BLOCKED:
                flags.append("⚠️ DOSING BLOCKED: High model uncertainty or risk profile prohibits pharmaceutical recommendations.")

        # ── Rule 6: clinical urgency score ───────────────────────────────────
        urgency = self._compute_urgency(disease_predictions, safety_level, model_uncertainty)

        return {
            "safety_level":          safety_level,
            "validated_predictions": validated,
            "safety_flags":          flags,
            "allow_dosing":          allow_dosing,
            "model_uncertainty":     model_uncertainty,
            "clinical_urgency":      urgency,
            "zoonotic_diseases":     zoonotic_found,
            "notifiable_diseases":   notifiable_found,
        }

    def validate_risk_assessment(
        self,
        risk_result: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Validate a risk-prediction result and augment with safety annotations."""
        enriched = dict(risk_result)
        flags: List[str] = []

        risk_level  = risk_result.get("risk_level", "low")
        uncertainty = risk_result.get("risk_uncertainty", 0)

        if risk_level == "high":
            flags.append("🔴 HIGH RISK detected — immediate veterinary examination advised.")
            existing_recs = enriched.get("recommendations", [])
            mandatory_rec = "MANDATORY: Contact attending veterinarian immediately."
            if mandatory_rec not in existing_recs:
                enriched["recommendations"] = [mandatory_rec] + existing_recs

        if uncertainty > 0.15:
            flags.append(
                f"Risk uncertainty ({uncertainty:.3f}) is elevated — "
                "repeat assessment recommended."
            )

        enriched["safety_flags"] = flags
        enriched["disclaimer"]   = self.DISCLAIMER
        return enriched

    def inject_disclaimer(self, report_text: str) -> str:
        """Ensure the clinical disclaimer appears at the end of any LLM report."""
        if self.DISCLAIMER[:40] in report_text:
            return report_text
        return f"{report_text}\n\n---\n{self.DISCLAIMER}"

    def check_image_quality(self, quality_report: Dict[str, Any]) -> Dict[str, Any]:
        if not quality_report.get("valid", True):
            return {
                "allowed": False,
                "reason":  "Image quality insufficient for reliable AI analysis.",
                "issues":  quality_report.get("issues") or [],
                "recommendations": quality_report.get("recommendations", []),
            }
        return {"allowed": True}

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _compute_urgency(
        self,
        predictions: List[Dict[str, Any]],
        safety_level: str,
        uncertainty: float,
    ) -> int:
        """Compute a clinical urgency score (1-10)."""
        base = {"pass": 2, "warning": 5, "blocked": 7}.get(safety_level, 3)

        disease_names = {p.get("disease", "") for p in predictions}
        if disease_names & self.NOTIFIABLE_DISEASES:
            base = min(base + 3, 10)
        elif disease_names & self.HIGH_RISK_DISEASES:
            base = min(base + 2, 10)

        max_conf = max((p.get("confidence", 0) for p in predictions), default=0)
        if max_conf > 0.80:
            base = min(base + 1, 10)
        if max_conf < 0.45:
            base = max(base - 1, 1)

        if uncertainty < 0.05:
            base = min(base + 1, 10)  # high certainty prediction

        return max(1, min(base, 10))
